#![allow(dead_code)]

use std::collections::HashMap;
use std::path::PathBuf;

/// A parsed theme from themes/palettes/*.toml
#[derive(Debug, Clone)]
pub struct Theme {
    pub name: String,
    pub path: PathBuf,
    /// Flattened key-value pairs for Tera context (e.g., "colors.core.background" -> "#1e1e2e")
    pub variables: HashMap<String, String>,
}

/// A discovered tool module from modules/<name>/
#[derive(Debug, Clone)]
pub struct Module {
    pub name: String,
    pub path: PathBuf,
    /// Key is OS identifier ("macos", "ubuntu"), value is list of package names
    pub packages_by_os: HashMap<String, Vec<String>>,
}

/// Output of the TUI phase — what the user selected
#[derive(Debug)]
pub struct UserSelection {
    pub selected_modules: Vec<Module>,
    pub selected_theme: Theme,
}

/// Actionable execution plan generated by engine.rs
#[derive(Debug)]
pub struct Plan {
    pub packages_to_install: Vec<String>,
    pub templates_to_render: Vec<TemplateJob>,
    pub symlinks_to_create: Vec<SymlinkJob>,
}

/// A single template file to be rendered via Tera
#[derive(Debug)]
pub struct TemplateJob {
    /// Source .tera file (e.g., modules/kitty/config/kitty/kitty.conf.tera)
    pub source: PathBuf,
    /// Rendered output destination (e.g., .rendered/kitty/config/kitty/kitty.conf)
    pub destination: PathBuf,
}

/// A single symlink to be created
#[derive(Debug)]
pub struct SymlinkJob {
    /// Absolute path of the source file (in .rendered/ or modules/)
    pub source_absolute: PathBuf,
    /// Absolute path where the symlink should be created (e.g., ~/.config/kitty/kitty.conf)
    pub target_absolute: PathBuf,
}
